export { default as AircraftPhotoSection } from './AircraftPhotoSection';
export { default as RouteSection } from './RouteSection';
export { default as TakeoffLandingSection } from './TakeoffLandingSection';
export { default as FlightDataSection } from './FlightDataSection';
export { default as FlightStatusSection } from './FlightStatusSection';
export { default as AircraftInfoSection } from './AircraftInfoSection';
export { default as ScheduleSection } from './ScheduleSection';
export { default as AltitudeGraphSection } from './AltitudeGraphSection';
export { default as PositionSection } from './PositionSection';
